export const MENU_URL = `https://www.swiggy.com/dapi/menu/pl?page-type=REGULAR_MENU&complete-menu=true&lat=12.9352403&lng=77.624532&restaurantId=`;
export const REST_CARD_URL = `https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/`;
export const REST_LIST = `https://www.swiggy.com/dapi/restaurants/list/v5?lat=12.9352403&lng=77.624532&is-seo-homepage-enabled=true&page_type=DESKTOP_WEB_LISTING`;
export const FOOTER_DATA = [
  {
    title: "Company",
    item: [
      "About Us",
      "Foodvilla Corporate",
      "Careers",
      "Team",
      "Foodvilla One",
      "Foodvilla Instamart",
      "Foodvilla Dineout",
      "Foodvilla Genie",
    ],
  },
  {
    title: "Contact Us",
    item: ["About Us", "Help & Support", "Partner with us", "Ride with us"],
  },
  {
    title: "Available In",
    item: ["Bangalore", "Gurgaon", "Hyderabad", "Delhi", "Mumbai", "Pune"],
    cities: [
        "Kolkata", "Chennai", "Ahmedabad", "Chandigarh", "Jaipur", "Kochi", "Coimbatore", "Lucknow", "Nagpur", "Vadodara",
        "Indore", "Guwahati", "Vizag", "Surat", "Dehradun", "Noida", "Ludhiana", "Trichy", "Vijayawada", "Kanpur", "Mysore",
        "Nashik", "Udaipur", "Pondicherry", "Agra", "Aurangabad", "Jalandhar", "Kota", "Madurai", "Allahabad", "Manipal", 
        "Amritsar", "Bareilly", "Meerut", "Bhopal", "Ooty", "Bhubaneswar", "Raipur", "Bikaner", "Rajkot", "Kozhikode", 
        "Central Goa", "Sirsa", "Gwalior", "Thrissur", "Kharagpur", "Tirupati", "Tirupur", "Vellore", "Thiruvananthapuram", 
        "Warangal", "Varanasi", "Mangaluru", "Patna", "Ranchi", "Faridabad", "Guntur", "Ujjain", "Patiala", "Karnal", "Kakinada", 
        "Rajahmundry", "Bilaspur", "Bhilai", "Anand", "Bhavnagar", "Jammu", "Muktsar", "Panipat", "Jamshedpur", "Dhanbad", 
        "Bokaro", "Hubli", "Belgaum", "Jabalpur", "Kolhapur", "Solapur", "Shillong", "Cuttack", "Aligarh", "Salem", "Agartala", 
        "Jodhpur", "Ajmer", "Jhansi", "Gorakhpur", "Thanjavur", "Erode", "Nellore", "Rourkela", "Anantapur", "Kurnool", 
        "Ahmednagar", "Phagwara", "Ambala", "Ballari", "Saharanpur", "Tirunelveli", "Bathinda", "Mathura", "Haridwar", 
        "Ratnagiri", "Sangli", "Amravati", "Rishikesh", "Nagercoil", "KanyaKumari", "Kadapa", "Nizamabad", "Shivamogga", 
        "Davanagere", "Roorkee", "Nanded", "Rewa", "Satna", "Shimla", "Muzaffarpur", "Valsad", "Vapi", "Chhapra", "Dharamshala", 
        "Kollam", "Silchar", "Alappuzha", "Sonipat", "Rohtak", "Mehsana", "Kullu", "Dhule", "Dharwad", "Latur", "Vizianagaram", 
        "Khammam", "Hampi", "Nainital", "Akola", "Kalaburagi", "Gaya", "Muzaffarnagar", "Dewas", "Korba", "Mussoorie", "Jalgaon", 
        "Yamuna Nagar", "Bhagalpur", "Hapur", "Morena", "Hassan", "Hisar", "Godhra", "Kolar", "Rampur", "Sitapur", "Etawah", 
        "Porbandar", "Nadiad", "Sagar", "Morbi", "Chhindwara", "Tumakuru", "Singrauli", "Thoothukudi", "Katni", "Khandwa", 
        "Eluru", "Malappuram", "Dibrugarh", "Deoghar", "Khanna", "Bidar", "Anantnag", "Madikeri", "Haldwani", "Panchkula", 
        "Farrukhabad", "Malegaon", "Dindigul", "Shahjahanpur", "Beed", "Junagadh", "Asansol", "Beawar", "Kishangarh", "Budhwal", 
        "Parbhani", "Gondia", "Ichalkaranji", "Jalna", "Yavatmal", "Shivpuri", "Moga", "Abohar", "Adoni", "Madanapalle", 
        "Tiruvannamalai", "Satara", "Ambur", "Karimnagar", "Ratlam", "Moradabad", "Machilipatnam", "Ongole", "Kottayam", 
        "Darbhanga", "Kurukshetra", "Unnao", "Bulandshahr", "Durgapur", "Siliguri", "Pali", "Tadepalligudem", "Ramagundam", 
        "Mahbubnagar", "Bhiwani", "Cuddalore", "Kaithal", "Jagtial", "Palakkad", "Guna", "Kumbakonam", "Maunath Bhanjan", 
        "Baripada", "Orai", "Bhadrak", "Batala", "Firozpur", "Barnala", "Raigarh", "Nagaon", "Mainpuri", "Balurghat", "Giridih", 
        "Ghazipur", "Jagdalpur", "Vidisha", "Dimapur", "Shikohabad", "Imphal", "Lakhimpur", "Rudrapur", "Ambikapur", "Damoh", 
        "Rae Bareli", "Tinsukia", "Rajapalayam", "Rajnandgaon", "Kashipur", "Ranibennur", "Burhanpur", "Bhadravati", "Chittoor", 
        "Pudukkottai", "Hardoi", "Basti", "Karaikkudi", "Lalitpur", "Hospet", "Budaun", "Neemuch", "Pilibhit", "Amroha", "Barshi", 
        "Sri Ganganagar", "Wardha", "Sehore", "Bhimavaram", "Hanumangarh", "Pathankot", "Puri", "Fatehpur", "Surendranagar Dudhrej", 
        "Jamnagar", "Bhuj", "Gandhidham", "Bharuch", "Navsari", "Amreli", "Palanpur", "Bhilwara", "Suratgarh", "Sikar", "Churu", 
        "Alwar", "Bhiwadi", "Bharatpur", "Mount Abu", "Bundi", "Sawai Madhopur", "Purulia", "Bardhaman", "Raniganj", "Darjeeling", 
        "Jalpaiguri", "Chittorgarh", "Dholpur", "Uluberia", "Nabadwip", "Bongaon", "Kanchrapara", "Bankura", "Habra", "Firozabad", 
        "Nalgonda", "Chandrapur", "Bijapur", "Bhusawal", "Raichur", "Bahraich", "Azamgarh", "Bahadurgarh", "Jind", "Rewari", 
        "Palwal", "Hathras", "Sambalpur", "Banda", "Hoshiarpur", "Faridkot", "Mandsaur", "Suryapet", "Adilabad", "Narasaraopet", 
        "Faizabad", "Tadpatri", "Gonda", "Mughalsarai", "Medinipur", "Nagda", "Chilakaluripet", "Hindupur", "Kasganj", "Raiganj", 
        "Deoria City", "Sultanpur", "Shamli", "Krishnanagar", "Ballia", "Guntakal", "Miryalaguda", "Etah", "Berhampore", "Gudivada", 
        "Haldia", "Santipur", "Basirhat", "Seoni", "Udgir", "Proddatur", "Nagapattinam", "Chikmagalur", "Chandausi", "Bhind", 
        "Mandya", "Bagalkot", "Nandurbar", "Chitradurga", "Osmanabad", "Modinagar", "Gadag-Betigeri", "Hoshangabad", "Jaunpur", 
        "Khurja", "Port Blair", "Jorhat", "Nandyal", "Biharsharif", "Buxar", "Siwan", "Dehri", "Bettiah", "Kishanganj", "Saharsa", 
        "Hajipur", "Motihari", "Sasaram", "Munger", "Katihar", "Arrah", "Srikakulam", "Begusarai", "Neyveli", "Waidhan", "Markapur", 
        "Chikkaballapur", "Bhatkal", "Gokak", "Itarsi", "Dabra", "Dhar", "Chalisgaon", "Thiruvallur", "Namakkal", "Dharmapuri", 
        "Bhandara", "Virudhunagar", "Siddipet", "Gadwal", "Bodhan-Rural", "Kamareddy", "Jhunjhunu", "Kapurthala", "Sangrur", 
        "Gurdaspur", "Ramgarh", "Bantwal", "Doddaballapura", "Buldana", "Karad", "Krishnagiri", "Tiptur", "Bhadrachalam", 
        "Mancherial", "Balrampur", "Bharabanki", "Malout", "Fatehgarh Sahib", "Ropar", "Nangal", "Narnaul", "Naraingarh", 
        "Himmatnagar", "Dausa", "Jahanabad", "Samastipur", "Purnea", "Berhampur", "Malda", "Tuni", "Puttur", "Rayachoty", 
        "Medak", "Nirmal", "Mirzapur", "Tanuku", "Dahod", "Barmer", "Gangapur City", "Mandi Gobindgarh", "Tarn Taran Sahib", 
        "Nakodar", "Ankleshwar", "Vyara", "Bardoli", "Halol", "Bijnor", "Sawantwadi", "Shrirampur", "Sangamner", "Baramati", 
        "Betul", "Chhatarpur", "Datia", "Balaghat", "Sivakasi", "Viluppuram", "Ramanathapuram", "Sirsi", "Kodaikanal", "Theni", 
        "Karur", "Karwar", "Sindhanur", "Kannur", "Noida 1", "Karunagappaly", "Thiruvalla", "Thodupuzha", "Kadiri", "Kavali", 
        "Tezpur", "Kayamkulam", "Kottarakkara", "Mandi Dabwali", "Fatehabad", "Jagraon", "Mansa", "Pinjore City", "Fazilka", 
        "Baddi", "Solan", "Daltonganj", "Balangir", "Paonta Sahib", "Kothagudem", "Hansi", "Aurangabad_Bihar", "Charkhi Dadri", 
        "Gopalganj", "Jharsuguda", "Tohana", "Jhalawar", "Sivasagar", "Bagdogra", "Angul", "Kendrapada", "Mallapuram", 
        "Veraval", "Daman", "Chiplun", "Silvassa", "Bapatla&Chirala", "Lonavla", "Bongaigaon", "Golaghat", "Duliajan", "Ramnagar", 
        "Bolpur", "Madhubani", "Balasore", "Palampur", "Kotdwar", "Koppal", "Chikhli", "Dahanu", "Itanagar", "Rangpo", "Aizawl", 
        "Gangtok", "Mayiladuthurai", "Kannauj", "Cooch Behar", "Jaigaon", "Palani", "Bilimora", "Udhampur", "Boisar", "Kohima", 
        "Naharlagun", "Dumka", "Rajsamand", "Gauriganj", "Bodinayakanur", "Bhawanipatna", "Baran", "Narsinghpur", "Uran Islampur", 
        "Kovilpatti", "Kasaragod", "Pusad", "Kendujhar", "Manali", "Diu", "Khamgaon", "Ramanagara", "Alipurduar", "Almora", 
        "Jhargram", "Arambagh", "Bhadohi", "Tenkasi", "Srivilliputhur", "Chidambaram", "Rajgarh", "Pratapgarh", "Washim", 
        "Mandi HP", "Ranaghat", "Raghunathpur", "Suri", "Kadayanallur", "Thiruvarur", "Ranaghat-WB", "Idukki", "Wayanad", 
        "Perambalur", "Paramakudi", "Khopoli", "Bela Pratapgarh", "Mahoba", "Sitamarhi", "Chakdaha", "Khalilabad", "Pattukkottai", 
        "Tindivanam", "Tiruttani", "Gangarampur", "Dharapuram", "Arakkonam", "Sirkali", "Aruppukottai", "Mettupalayam", "Digboi", 
        "Biswanath Chariali", "Nalbari", "Shirdi city", "Mukerian", "Hosur", "Palakollu", "Amalapuram", "Ravulapalem", 
        "Narsipatnam", "Barh", "Palghar", "Shahdol", "Kushalnagar", "Dungarpur", "Chaibasa", "Haveri", "Karaikal", "Jjajjar", 
        "Kokrajhar", "Rangia", "Hamirpur", "Una", "Sulthan Bathery", "Rayagada", "Paradeep", "Mandapeta", "Jamui", "Pilkhuwa", 
        "Parvathipuram", "Ambajogai", "Araria", "North Lakhimpur", "Rajampet", "Udumalaipettai", "Tirupattur", "Hojai", "Khagaria", 
        "Dasuya", "Gudur", "Sullurpeta", "Piler", "SankaranKoil", "Nabha", "LPU - Phagwara", "Jangipur", "Roha", "Maharajganj", 
        "Kallakurichi", "Kalimpong", "Sundernagar", "Nawada", "Forbesganj", "Mokameh Khas", "Bazpur", "Lakhisarai", "Rameswaram", 
        "Sahjanwa", "Siddharthnagar", "Nanjangud", "Chamarajanagar", "Kurali", "Sundar Nagar", "Bobbili", "Jangaon", "Banswara", 
        "Sundergarh", "Godda", "Madhupur", "Katwa", "Dhupguri", "Contai", "Baramulla", "Kangeyam", "Naugachia", "Madhepura", 
        "Jamkhambhaliya", "Mundra", "Patan", "Mahuva", "Attur", "Pen", "Mandla", "Sidhi", "Lakshadweep", "Chitrakoot", "Rajam", 
        "Nippani", "Sankeshwar", "Chikkodi", "Modasa", "Bavla", "Puttur_AP", "Sinnar", "singur", "Nelamangala", "Srinagar Uttarakhand", 
        "Dhampur"
      ]
  },
  {
    title: "Life at Foodvilla",
    item: ["About Us", "Explore with Foodvilla", "Foodvilla News", "Snackables"],
  },
  {
    title: "Legal",
    item: ["About Us", "Explore with Foodvilla", "Foodvilla News", "Snackables"],
  },
  {
    title: "Social Links",
    item: ["Linked In", "Instagram", "Facebook", "Twitter"],
  },
];
